export const EnvKeyConstant = {
  RAG_FOLDER_DATA_PATH: 'RAG_FOLDER_DATA_PATH',
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  RAG_LIMIT_FILE_COUNT: 'RAG_LIMIT_FILE_COUNT',
  RAG_LIMIT_FILE_SIZE: 'RAG_LIMIT_FILE_SIZE',
  GOOGLE_API_KEY: 'GOOGLE_API_KEY',
  QDRANT_URL: 'QDRANT_URL',
  QDRANT_COLLECTION: 'QDRANT_COLLECTION',
  OPENAI_MODEL: 'OPENAI_MODEL',
  OPENAI_EMBEDDING_MODEL: 'OPENAI_EMBEDDING_MODEL',
};
