export const EnvKeyConstant = {
  RAG_FOLDER_DATA_PATH: 'RAG_FOLDER_DATA_PATH',
  OPEN_AI_API_KEY: 'OPEN_AI_API_KEY',
  RAG_LIMIT_FILE_COUNT: 'RAG_LIMIT_FILE_COUNT',
  RAG_LIMIT_FILE_SIZE: 'RAG_LIMIT_FILE_SIZE',
};
